config/routes.rb
Rails.application.routes.draw do
 
  post 'searchResults', to: 'search_results#create'
  get 'homes', to: 'homes#index'

  #get 'password_resets/new'
  #get 'password_resets/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  get '/about',  to: 'welcome#about'
  get '/signup', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :likes, only: [:index,:create,:destroy]
end

app/views/shared/_mobile_menu.html.erb
<div id="mobile-menu">
	<div style="text-align: center;margin-top:0.8em">

		<%= link_to root_url do%>
			<%=image_tag 'logo.svg', :class =>"logo"%>
		<%end%>

		<%if current_user%>
			<div id="user-info">
				<ul>
					<li><%=gravatar_for(current_user,size: 15)%>
				        <%=link_to current_user.email, edit_user_path(current_user), id:""%>
                    </li>
				    <li><%=link_to "Saved Homes", likes_path%></li>
				</ul>
			</div>
			<div class="line"></div>
		<%end%>

        <div id="general">
            <ul>
            <li><%=form_tag(homes_path, method: "get") do%>
                
                <%=hidden_field_tag 'listingType', 'buy'%>
                <%=hidden_field_tag 'filterText', 'Jersey City'%>
                <%=submit_tag("Buy")%>
            
            <%end%></li>

            <li><%=form_tag(homes_path, method: "get") do%>
            
                <%=hidden_field_tag 'listingType', 'rent'%>
                <%=hidden_field_tag 'filterText', 'Jersey City'%>
                <%=submit_tag("Rent")%>
            <%end%></li>

            <li style="padding-left: 5px;"><%= link_to "About", about_path%></li>
            </ul>
        </div>
	</div>
	<%if(current_user)%>
		<%=button_to 'Logout', logout_url, method: :delete%>
	<%else%>
		<%=button_to 'Sign up/Sign in', signup_path, method: :get%>
	<%end%>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
	<a href=<%=root_url%> ><%= image_tag 'logo.svg', :class => "logo"%></a>
	<div class="navbar-links left" >
		<span>
			<%=form_tag(homes_path, method: "get") do%>
                
                <%=hidden_field_tag 'listingType', 'buy'%>
                <%=hidden_field_tag 'filterText', 'Jersey City'%>
                <%=submit_tag("Buy")%>
            <%end%>
		</span>
		<span>
			<%=form_tag(homes_path, method: "get") do%>
                <%=hidden_field_tag 'listingType', 'rent'%>
                <%=hidden_field_tag 'filterText', 'Jersey City'%>
                <%=submit_tag("Rent")%>
            <%end%>
		</span>
		<span><%=link_to 'About', about_path%></span>
	</div>

	<div class="navbar-links">
		<%if current_user%>
			<span><%=link_to "Saved Homes", likes_path%></span>
			<div class="dropdown">
			<span><%=gravatar_for current_user,size: 30%>
				<%=link_to current_user.email, edit_user_path(current_user), id:""%>
				  </span>
				  <div class="dropdown-content">
				  	<ul>
				  	<li><%= link_to "Edit Profile", edit_user_path(current_user)%></li>
				  	<li><%=button_to 'Logout', logout_url, method: :delete%></li>
				  	</ul>
				  </div>
				</div>
               
		<%else%>
			<span><%=link_to "Saved Homes", signup_path%></span>
			<span>
				<%=link_to "Sign In", login_path, id:"signin-btn"%>
            </span>	
		<%end%>
	</div>
</div>
<div id="menu-btn" onclick="toggleMenu()">
		<span class="bar1"></span>
		<span class="bar2"></span>
		<span class="bar3"></span>
	</div>